# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
kotlinVersion=2.3.21
mod_version=1.4.3
maven_group=com.algorithmlx
archivesName=DimOre
mod_license=ARR
mod_credits=
mod_authors=AlgorithmLX

mod.id=dimore
mod.name=Dimensional Ores
mod.version=1.4.3
mod.group=com.algorithmlx
mod.description=Add ores to your dimensions!

# Publish projects
modrinth_project=tdrqr7qS
curseforge_project=548552

# Common versions
flk_version=1.13.11
klf_loader_version=3.1
klf_version=2.12.1
