# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
# Mod properties
kotlinVersion=2.3.0
mod_version=1.4.0
maven_group=com.algorithmlx
archivesName=DimOre
mod_name=Dimensional Ores
mod_id=dimore
mod_license=ARR
mod_credits=
mod_description=
mod_authors=AlgorithmLX

modrinth_project=tdrqr7qS
curseforge_project=548552
