modLoader="kotlinforforge"
loaderVersion="[4.10,)"
license="MIT"

[[mods]]
    modId="dimore"
    version="${file.jarVersion}"
    displayName="Dimensional Ores"
    displayURL="https://0mods.team"
    authors="AlgorithmLX"
    description='''Ore in dimensions'''
[[dependencies.dimore]]
    modId="forge"
    mandatory=true
    versionRange="[45.2.8,46.0.0)"
    ordering="NONE"
    side="BOTH"#
[[dependencies.dimore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimore]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.10.0,)"
    ordering="NONE"
    side="BOTH"