modLoader="kotlinforforge"
loaderVersion="[3.12,)"
license="MIT"

[[mods]]
    modId="dimore"
    version="${file.jarVersion}"
    displayName="Dimensional Ores"
    displayURL="https://0mods.team"
    authors="AlgorithmLX"
    description='''Ore in dimensions'''
[[dependencies.dimore]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.1,44.0.0)"
    ordering="NONE"
    side="BOTH"#
[[dependencies.dimore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimore]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3.12.0,)"
    ordering="NONE"
    side="BOTH"