modLoader = "klf"
loaderVersion = "[${klf_version},)"
issueTrackerURL = "https://github.com/${mod_author}/${mod_name}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "${mod_id}-logo.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"