name: Publish mod to platforms
on:
  push:
    branches: [ "stonecutter" ]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: Generate Changelog
        uses: smichard/conventional_changelog@2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
      - name: Set Git User Info
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
          git push
  curseforge:
    name: CurseForge Publish
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    if: |
      contains(github.event.head_commit.message, '[cf]')
    needs: changelog
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14.2'
      - name: Build Mod
        run: gradle publishUnified
        env:
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          CURSE_PROJECT: ${{ secrets.CURSE_PROJECT }}
  modrinth:
    name: Modrinth Publish
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    if: |
      contains(github.event.head_commit.message, '[mr]')
    needs: changelog
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14.2'
      - name: Build Mod
        run: gradle publishUnified
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT: ${{ secrets.MODRINTH_PROJECT }}
